---
- hosts: ec2
  become: yes
  tasks:
    - name: Update APT package manager
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    - name: Start Prometheus
      systemd:
        name: prometheus
        state: started
        enabled: yes

    - name: Install Grafana
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Add Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        update_cache: yes
        state: present

    - name: Start Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: yes
